# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wah Yan SA' do

pod’Firebase’
pod’Firebase/Messaging’
pod’Firebase/Database’
pod’Firebase/Core’
pod'Firebase/RemoteConfig'

end
